name: Build DemoApp

on:
  push:
    paths-ignore:
    - '.github/**'
    branches:
      - 'release/**'
  pull_request:
    paths-ignore:
    - '.github/**'
    branches:
      - 'develop'
      - 'release'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-test:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yaml
    with:
      working-directory: docker-demo
      context: ./demoapp
    secrets: inherit
