name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: nginx
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get Current Branch
        run: |
         echo  ${{ steps.branch-name.outputs.current_branch }} >> $GITHUB_ENV

      - name: Get Image Info
        run: |
          echo IMAGE_NAME=${{ inputs.image-names }} >> $GITHUB_ENV
          echo IMAGE_TAG=${{steps.meta.outputs.image.version}} >> $GITHUB_ENV

      - name: Invoke UpdateImageTag Workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GH_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/chris201222/platform-config/dispatches \
          -d '{"event_type":"update-image-tag","client_payload":{"imageName": "ks-guestbook-demo", "imageTag": "1.0"}}'
          # -d '{"event_type":"update-image-tag","client_payload":{"imageName": "'"$IMAGE_NAME"'", "imageTag": "'"$IMAGE_TAG"'"}}'
