name: Docker Image CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'main'
  #   tags:
  #     - 'v*'
  # pull_request:
  #   branches:
  #     - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nginx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: nginx
      #     # push: ${{ github.event_name != 'pull_request' }}
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Docker Build
        id: build_image
        run: |
          docker build -t ghcr.io/nginx:${{ github.run_number }} -f nginx/Dockerfile .
          
      # - name: Docker Push
      #   id: push_image
      #   run: |
      #     docker push ghcr.io/nginx:${{ github.run_number }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: chris201222/platform-config
          event-type: update-image-tag
          client-payload: '{"imageName": nginx, "IMAGE_TAG": "${{ github.run_number }}", "currentBranch": "${{ steps.branch-name.outputs.current_branch }}" }'
