name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: nginx
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print current branch
        run: |
         echo  ${{ steps.branch-name.outputs.current_branch }}
